import os
os.environ['DJANGO_SETTINGS_MODULE']='settings'
import webapp2 as webapp
from google.appengine.ext.webapp.util import run_wsgi_app
from google.appengine.ext.webapp import template
from google.appengine.api import users
from google.appengine.ext import db
import cgi
import cgitb
cgitb.enable()
import datetime
from ubertool.aquatic_toxicity import AquaticToxicity
import logging


class UbertoolAquaticToxicityConfigurationPage(webapp.RequestHandler):
    def post(self):
        logger = logging.getLogger("UbertoolAquaticToxicityConfigurationPage")
        form = cgi.FieldStorage()
        #config_name = 
        #user = users.get_current_user()
        #q = db.Query(AquaticToxicity)
        #q.filter('user =',user)
        #q.filter("config_name =", config_name)
        #aquatic_toxicity = q.get()
        #if aquatic_toxicity is None:
        #    aquatic_toxicity = AquaticToxicity()
        #if user:
        #    logger.info(user.user_id())
        #    aquatic_toxicity.user = user
        #aquatic_toxicity = []
        #aquatic_toxicity['config_name'] = str(form.getvalue('config_name'))
        #aquatic_toxicity['acute_toxicity_target_concentration_for_freshwater_fish'] = float(form.getvalue('acute_toxicity_target_concentration_for_freshwater_fish'))
        #aquatic_toxicity['chronic_toxicity_target_concentration_for_freshwater_fish'] = float(form.getvalue('chronic_toxicity_target_concentration_for_freshwater_fish'))
        #aquatic_toxicity['acute_toxicity_target_concentration_for_freshwater_invertebrates'] = float(form.getvalue('acute_toxicity_target_concentration_for_freshwater_invertebrates'))
        #aquatic_toxicity['chronic_toxicity_target_concentration_for_freshwater_invertebrates'] = float(form.getvalue('chronic_toxicity_target_concentration_for_freshwater_invertebrates'))   
        #aquatic_toxicity['toxicity_target_concentration_for_nonlisted_vascular_plants'] = float(form.getvalue('toxicity_target_concentration_for_nonlisted_vascular_plants'))
        #aquatic_toxicity['toxicity_target_concentration_for_listed_vascular_plants'] = float(form.getvalue('toxicity_target_concentration_for_listed_vascular_plants'))
        #aquatic_toxicity['toxicity_target_concentration_for_duckweed'] = float(form.getvalue('toxicity_target_concentration_for_duckweed'))
        aquatic_toxicity['lf_p_sediment'] = float(form.getvalue('lf_p_sediment'))
        aquatic_toxicity['lf_p_phytoplankton'] = float(form.getvalue('lf_p_phytoplankton'))
        aquatic_toxicity['lf_p_zooplankton'] = float(form.getvalue('lf_p_zooplankton'))
        aquatic_toxicity['lf_p_benthic_invertebrates'] = float(form.getvalue('lf_p_benthic_invertebrates'))
        aquatic_toxicity['lf_p_filter_feeders'] = float(form.getvalue('lf_p_filter_feeders'))
        aquatic_toxicity['lf_p_small_fish'] = float(form.getvalue('lf_p_small_fish'))
        aquatic_toxicity['lf_p_medium_fish'] = float(form.getvalue('lf_p_medium_fish'))
        aquatic_toxicity['mf_p_sediment'] = float(form.getvalue('mf_p_sediment'))
        aquatic_toxicity['mf_p_phytoplankton'] = float(form.getvalue('mf_p_phytoplankton'))
        aquatic_toxicity['mf_p_zooplankton'] = float(form.getvalue('mf_p_zooplankton'))
        aquatic_toxicity['mf_p_benthic_invertebrates'] = float(form.getvalue('mf_p_benthic_invertebrates'))
        aquatic_toxicity['mf_p_filter_feeders'] = float(form.getvalue('mf_p_filter_feeders'))
        aquatic_toxicity['mf_p_small_fish'] = float(form.getvalue('mf_p_small_fish'))
        aquatic_toxicity['sf_p_sediment'] = float(form.getvalue('sf_p_sediment'))
        aquatic_toxicity['sf_p_phytoplankton'] = float(form.getvalue('sf_p_phytoplankton'))
        aquatic_toxicity['sf_p_zooplankton'] = float(form.getvalue('sf_p_zooplankton'))
        aquatic_toxicity['sf_p_benthic_invertebrates'] = float(form.getvalue('sf_p_benthic_invertebrates'))
        aquatic_toxicity['sf_p_filter_feeders'] = float(form.getvalue('sf_p_filter_feeders'))
        aquatic_toxicity['ff_p_sediment'] = float(form.getvalue('ff_p_sediment'))
        aquatic_toxicity['ff_p_phytoplankton'] = float(form.getvalue('ff_p_phytoplankton'))
        aquatic_toxicity['ff_p_zooplankton'] = float(form.getvalue('ff_p_zooplankton'))
        aquatic_toxicity['ff_p_benthic_invertebrates'] = float(form.getvalue('ff_p_benthic_invertebrates'))
        aquatic_toxicity['beninv_p_sediment'] = float(form.getvalue('beninv_p_sediment'))
        aquatic_toxicity['beninv_p_phytoplankton'] = float(form.getvalue('beninv_p_phytoplankton'))
        aquatic_toxicity['beninv_p_zooplankton'] = float(form.getvalue('beninv_p_zooplankton'))
        aquatic_toxicity['zoo_p_sediment'] = float(form.getvalue('zoo_p_sediment'))
        aquatic_toxicity['zoo_p_phytoplankton'] = float(form.getvalue('zoo_p_phytoplankton'))
        aquatic_toxicity['s_lipid'] = float(form.getvalue('s_lipid'))
        aquatic_toxicity['s_NLOM'] = float(form.getvalue('s_NLOM'))
        aquatic_toxicity['s_water'] = float(form.getvalue('s_water'))
        aquatic_toxicity['v_lb_phytoplankton'] = float(form.getvalue('v_lb_phytoplankton'))
        aquatic_toxicity['v_nb_phytoplankton'] = float(form.getvalue('v_nb_phytoplankton'))
        aquatic_toxicity['v_wb_phytoplankton'] = float(form.getvalue('v_wb_phytoplankton'))
        aquatic_toxicity['v_lb_zoo'] = float(form.getvalue('v_lb_zoo'))
        aquatic_toxicity['v_nb_zoo'] = float(form.getvalue('v_nb_zoo'))
        aquatic_toxicity['v_wb_zoo'] = float(form.getvalue('v_wb_zoo'))
        aquatic_toxicity['v_lb_beninv'] = float(form.getvalue('v_lb_beninv'))
        aquatic_toxicity['v_nb_beninv'] = float(form.getvalue('v_nb_beninv'))
        aquatic_toxicity['v_wb_beninv'] = float(form.getvalue('v_wb_beninv'))
        aquatic_toxicity['v_lb_ff'] = float(form.getvalue('v_lb_ff'))
        aquatic_toxicity['v_nb_ff'] = float(form.getvalue('v_nb_ff'))
        aquatic_toxicity['v_wb_ff'] = float(form.getvalue('v_wb_ff'))
        aquatic_toxicity['v_lb_sf'] = float(form.getvalue('v_lb_sf'))
        aquatic_toxicity['v_nb_sf'] = float(form.getvalue('v_nb_sf'))
        aquatic_toxicity['v_wb_sf'] = float(form.getvalue('v_wb_sf'))
        aquatic_toxicity['v_lb_mf'] = float(form.getvalue('v_lb_mf'))
        aquatic_toxicity['v_nb_mf'] = float(form.getvalue('v_nb_mf'))
        aquatic_toxicity['v_wb_mf'] = float(form.getvalue('v_wb_mf'))
        aquatic_toxicity['v_lb_lf'] = float(form.getvalue('v_lb_lf'))
        aquatic_toxicity['v_nb_lf'] = float(form.getvalue('v_nb_lf'))
        aquatic_toxicity['v_wb_lf'] = float(form.getvalue('v_wb_lf'))
        aquatic_toxicity['k1_phytoplankton'] = float(form.getvalue('k1_phytoplankton'))
        aquatic_toxicity['k2_phytoplankton'] = float(form.getvalue('k2_phytoplankton'))
        aquatic_toxicity['ke_phytoplankton'] = float(form.getvalue('ke_phytoplankton'))
        aquatic_toxicity['kd_phytoplankton'] = float(form.getvalue('kd_phytoplankton'))
        aquatic_toxicity['km_phytoplankton'] = float(form.getvalue('km_phytoplankton'))
        aquatic_toxicity['k1_zoo'] = float(form.getvalue('k1_zoo'))
        aquatic_toxicity['k2_zoo'] = float(form.getvalue('k2_zoo'))
        aquatic_toxicity['ke_zoo'] = float(form.getvalue('ke_zoo'))
        aquatic_toxicity['kd_zoo'] = float(form.getvalue('kd_zoo'))
        aquatic_toxicity['km_zoo'] = float(form.getvalue('km_zoo'))
        aquatic_toxicity['k1_beninv'] = float(form.getvalue('k1_beninv'))
        aquatic_toxicity['k2_beninv'] = float(form.getvalue('k2_beninv'))
        aquatic_toxicity['ke_beninv'] = float(form.getvalue('ke_beninv'))
        aquatic_toxicity['kd_beninv'] = float(form.getvalue('kd_beninv'))
        aquatic_toxicity['km_beninv'] = float(form.getvalue('km_beninv'))
        aquatic_toxicity['k1_ff'] = float(form.getvalue('k1_ff'))
        aquatic_toxicity['k2_ff'] = float(form.getvalue('k2_ff'))
        aquatic_toxicity['ke_ff'] = float(form.getvalue('ke_ff'))
        aquatic_toxicity['kd_ff'] = float(form.getvalue('kd_ff'))
        aquatic_toxicity['km_ff'] = float(form.getvalue('km_ff'))
        aquatic_toxicity['k1_sf'] = float(form.getvalue('k1_sf'))
        aquatic_toxicity['k2_sf'] = float(form.getvalue('k2_sf'))
        aquatic_toxicity['ke_sf'] = float(form.getvalue('ke_sf'))
        aquatic_toxicity['kd_sf'] = float(form.getvalue('kd_sf'))
        aquatic_toxicity['km_sf'] = float(form.getvalue('km_sf'))
        aquatic_toxicity['k1_mf'] = float(form.getvalue('k1_mf'))
        aquatic_toxicity['k2_mf'] = float(form.getvalue('k2_mf'))
        aquatic_toxicity['ke_mf'] = float(form.getvalue('ke_mf'))
        aquatic_toxicity['kd_mf'] = float(form.getvalue('kd_mf'))
        aquatic_toxicity['km_mf'] = float(form.getvalue('km_mf'))
        aquatic_toxicity['k1_lf'] = float(form.getvalue('k1_lf'))
        aquatic_toxicity['k2_lf'] = float(form.getvalue('k2_lf'))
        aquatic_toxicity['ke_lf'] = float(form.getvalue('ke_lf'))
        aquatic_toxicity['kd_lf'] = float(form.getvalue('kd_lf'))
        aquatic_toxicity['km_lf'] = float(form.getvalue('km_lf'))
        aquatic_toxicity['s_respire'] = float(form.getvalue('s_respire'))
        aquatic_toxicity['phyto_respire'] = float(form.getvalue('phyto_respire'))
        aquatic_toxicity['zoo_respire'] = float(form.getvalue('zoo_respire'))
        aquatic_toxicity['beninv_respire'] = float(form.getvalue('beninv_respire'))
        aquatic_toxicity['ff_respire'] = float(form.getvalue('ff_respire'))
        aquatic_toxicity['sfish_respire'] = float(form.getvalue('sfish_respire'))
        aquatic_toxicity['mfish_respire'] = float(form.getvalue('mfish_respire'))
        aquatic_toxicity['lfish_respire'] = float(form.getvalue('lfish_respire'))
        aquatic_toxicity['mo_phytoplankton'] = float(form.getvalue('mo_phytoplankton'))
        aquatic_toxicity['mp_phytoplankton'] = float(form.getvalue('mp_phytoplankton'))
        aquatic_toxicity['kg_phytoplankton'] = float(form.getvalue('kg_phytoplankton'))
        self.redirect("terrestrial_toxicity.html")
        
app = webapp.WSGIApplication([('/.*', UbertoolAquaticToxicityConfigurationPage)], debug=True)

def main():
    run_wsgi_app(app)

if __name__ == '__main__':
    main()

