function gui(){var Y='',V=' top: -1000px;',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',cb='");',ub='#',lc='.cache.js',wb='/',Cb='//',Zb='04CA7F68F12302BA6246B3B73AC688F1',gc='3B416AB4B314C80A74F223402840D70D',hc='4FB410D3237A520BE544D6CD1175EC32',kc=':',_b=':1',ac=':2',bc=':3',cc=':4',dc=':5',ec=':6',fc=':7',lb='::',X='<!doctype html>',Z='<html><head><\/head><body><\/body><\/html>',ob='=',vb='?',qb='Bad handler "',ic='C137422CD3212B2241B65E334B7204F8',W='CSS1Compat',ab='Chrome',_='DOMContentLoaded',Q='DUMMY',jc='EBF5B6CACD1C0A5205721DE3EE811DA4',Bb='base',zb='baseUrl',L='begin',R='body',K='bootstrap',yb='clear.cache.gif',Db='clipboardData.access',tc='common/canvas.css',wc='common/error.css',sc='common/global.css',vc='common/periodicsystem.css',uc='common/toolbar.css',nb='content',Ob='default',xc='end',bb='eval("',Fb='event',$b='foobar',Vb='gecko',Gb='gecko.variant',Ib='gecko1_8',O='gui',Yb='gui.devmode.js',Ab='gui.nocache.js',kb='gui::',M='gwt.codesvr.gui=',N='gwt.codesvr=',rc='gwt/clean/clean.css',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',hb='head',pc='href',Sb='ie10',Lb='ie11',Ub='ie8',Tb='ie9',S='iframe',xb='img',eb='javascript',T='javascript:""',mc='link',qc='loadExternalRefs',ib='meta',gb='moduleRequested',fb='moduleStartup',Rb='msie',jb='name',Jb='none',Nb='onLoad',U='position:absolute; width:0; height:0; border:none; left: -1000px;',nc='rel',Qb='safari',db='script',Xb='selectingPermutation',P='startup',Mb='std',oc='stylesheet',Kb='trident',$='undefined',Wb='unknown',Hb='user.agent',Pb='webkit',Eb='window';var o=window;var p=document;r(K,L);function q(){var a=o.location.search;return a.indexOf(M)!=-1||a.indexOf(N)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:O,sessionId:o.__gwtStatsSessionId,subSystem:P,evtGroup:a,millis:(new Date).getTime(),type:b})}}
gui.__sendStats=r;gui.__moduleName=O;gui.__errFn=null;gui.__moduleBase=Q;gui.__softPermutationId=0;gui.__computePropValue=null;gui.__getPropMap=null;gui.__gwtInstallCode=function(){};gui.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[O]={moduleName:O};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(R)[0]}
function B(){if(v){return}var a=p.createElement(S);a.src=T;a.id=O;a.style.cssText=U+V;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==W?X:Y;v.write(b+Z);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==$){return typeof p.body!=$&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(_,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(_,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(bb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(cb));g=f.createElement(db);g.language=eb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(db);g.language=eb;g.text=c[i];e.appendChild(g);d(e,g)}}}
gui.onScriptDownloaded=function(a){l(function(){m(a)})};r(fb,gb);var n=p.createElement(db);n.src=k;p.getElementsByTagName(hb)[0].appendChild(n)}
gui.__startLoadingFragment=function(a){return G(a)};gui.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(db);c.language=eb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,Y);if(j.indexOf(lb)>=0){continue}if(j==mb){k=i.getAttribute(nb);if(k){var l,m=k.indexOf(ob);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Y}c[j]=l}}else if(j==pb){k=i.getAttribute(nb);if(k){try{d=eval(k)}catch(a){alert(qb+k+rb)}}}else if(j==sb){k=i.getAttribute(nb);if(k){try{e=eval(k)}catch(a){alert(qb+k+tb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;gui.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(ub);if(b==-1){b=a.length}var c=a.indexOf(vb);if(c==-1){c=a.length}var d=a.lastIndexOf(wb,Math.min(c,b));return d>=0?a.substring(0,d+1):Y}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(xb);b.src=a+yb;a=e(b.src)}return a}
function g(){var a=t(zb);if(a!=null){return a}return Y}
function h(){var a=p.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ab)!=-1){return e(a[b].src)}}return Y}
function i(){var a=p.getElementsByTagName(Bb);if(a.length>0){return a[a.length-1].href}return Y}
function j(){var a=p.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Y){k=h()}if(k==Y){k=i()}if(k==Y&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return gui.__moduleBase+a}
function H(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Db]=function(){if(!!window.clipboardData){return Eb}else{return Fb}};i[Db]={event:0,window:1};j[Gb]=function(){try{if(!j.hasOwnProperty(Hb)||k(Hb)!==Ib){return Jb}}catch(a){return Jb}if(navigator.userAgent.toLowerCase().indexOf(Kb)!=-1){return Lb}return Mb};i[Gb]={ie11:0,none:1,std:2};j[Nb]=function(){o.marvin={onLoadArray:[],onLoad:function(){if(!o.marvin.onLoadArray){return}for(var a=0;a<o.marvin.onLoadArray.length;a++)o.marvin.onLoadArray[a]();delete o.marvin.onLoadArray},onReady:function(a){o.marvin.onLoadArray?o.marvin.onLoadArray.push(a):a()}};return Ob};i[Nb]={'default':0,foobar:1};j[Hb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Pb)!=-1}())return Qb;if(function(){return b.indexOf(Rb)!=-1&&p.documentMode>=10}())return Sb;if(function(){return b.indexOf(Rb)!=-1&&p.documentMode>=9}())return Tb;if(function(){return b.indexOf(Rb)!=-1&&p.documentMode>=8}())return Ub;if(function(){return b.indexOf(Vb)!=-1}())return Ib;return Wb};i[Hb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4,unknown:5};s=function(a,b){return b in i[a]};gui.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};gui.__computePropValue=k;o.__gwt_activeModules[O].bindings=gui.__getPropMap;r(K,Xb);if(q()){return G(Yb)}var l;try{h([Fb,Jb,Ob,Qb],Zb);h([Fb,Jb,$b,Qb],Zb);h([Fb,Jb,Ob,Wb],Zb+_b);h([Fb,Jb,$b,Wb],Zb+_b);h([Eb,Jb,Ob,Qb],Zb+ac);h([Eb,Jb,$b,Qb],Zb+ac);h([Eb,Jb,Ob,Wb],Zb+bc);h([Eb,Jb,$b,Wb],Zb+bc);h([Fb,Jb,Ob,Qb],Zb+cc);h([Fb,Jb,$b,Qb],Zb+cc);h([Fb,Jb,Ob,Wb],Zb+dc);h([Fb,Jb,$b,Wb],Zb+dc);h([Eb,Jb,Ob,Qb],Zb+ec);h([Eb,Jb,$b,Qb],Zb+ec);h([Eb,Jb,Ob,Wb],Zb+fc);h([Eb,Jb,$b,Wb],Zb+fc);h([Fb,Lb,Ob,Ib],gc);h([Fb,Lb,$b,Ib],gc);h([Fb,Mb,Ob,Ib],gc+_b);h([Fb,Mb,$b,Ib],gc+_b);h([Eb,Lb,Ob,Ib],gc+ac);h([Eb,Lb,$b,Ib],gc+ac);h([Eb,Mb,Ob,Ib],gc+bc);h([Eb,Mb,$b,Ib],gc+bc);h([Fb,Lb,Ob,Ib],gc+cc);h([Fb,Lb,$b,Ib],gc+cc);h([Fb,Mb,Ob,Ib],gc+dc);h([Fb,Mb,$b,Ib],gc+dc);h([Eb,Lb,Ob,Ib],gc+ec);h([Eb,Lb,$b,Ib],gc+ec);h([Eb,Mb,Ob,Ib],gc+fc);h([Eb,Mb,$b,Ib],gc+fc);h([Fb,Jb,Ob,Sb],hc);h([Fb,Jb,$b,Sb],hc);h([Eb,Jb,Ob,Sb],hc+_b);h([Eb,Jb,$b,Sb],hc+_b);h([Fb,Jb,Ob,Sb],hc+ac);h([Fb,Jb,$b,Sb],hc+ac);h([Eb,Jb,Ob,Sb],hc+bc);h([Eb,Jb,$b,Sb],hc+bc);h([Fb,Jb,Ob,Ub],ic);h([Fb,Jb,$b,Ub],ic);h([Eb,Jb,Ob,Ub],ic+_b);h([Eb,Jb,$b,Ub],ic+_b);h([Fb,Jb,Ob,Ub],ic+ac);h([Fb,Jb,$b,Ub],ic+ac);h([Eb,Jb,Ob,Ub],ic+bc);h([Eb,Jb,$b,Ub],ic+bc);h([Fb,Jb,Ob,Tb],jc);h([Fb,Jb,$b,Tb],jc);h([Eb,Jb,Ob,Tb],jc+_b);h([Eb,Jb,$b,Tb],jc+_b);h([Fb,Jb,Ob,Tb],jc+ac);h([Fb,Jb,$b,Tb],jc+ac);h([Eb,Jb,Ob,Tb],jc+bc);h([Eb,Jb,$b,Tb],jc+bc);l=f[k(Db)][k(Gb)][k(Nb)][k(Hb)];var m=l.indexOf(kc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}gui.__softPermutationId=g;return G(l+lc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(mc);b.setAttribute(nc,oc);b.setAttribute(pc,G(a));p.getElementsByTagName(hb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(qc,L);c(rc);c(sc);c(tc);c(uc);c(vc);c(wc);r(qc,xc)}
D();gui.__moduleBase=F();u[O].moduleBase=gui.__moduleBase;var J=H();I();r(K,xc);C(J);return true}
gui.succeeded=gui();