# -*- coding: utf-8 -*-
"""
Created on Tue Jan 31 11:55:40 2012

@author: jharston
"""
import os
os.environ['DJANGO_SETTINGS_MODULE']='settings'
from django import forms
from django.db import models
from google.appengine.api import users
from google.appengine.ext import db
from aquatic_toxicity import AquaticToxicity
import datetime

class ATInp(forms.Form):
    #user_id = users.get_current_user().user_id()
    #user = users.get_current_user()
    #user_id = user.user_id()
    #q = db.Query(AquaticToxicity)
    #q.filter('user =',user)
    #uses = ()
    #uses += ((None,None),)
    #for use in q:
        #logger.info(use.to_xml())
    #    uses += ((use.config_name,use.config_name),)
    user_aqua_configuration = forms.ChoiceField(label="Aquatic Toxicity Saved Use Configuration",required=True)
    config_name = forms.CharField(label="Aquatic Toxicity Configuration Name", initial="aquatic-toxicity-config-%s"%datetime.datetime.now())
    acute_toxicity_target_concentration_for_freshwater_fish = forms.FloatField(label='Acute Toxicity Target Concentration For Most Sensitive Freshwater Fish')
    chronic_toxicity_target_concentration_for_freshwater_fish = forms.FloatField(label='Chronic Toxicity Target Concentration For Most Sensitive Freshwater Fish')
    acute_toxicity_target_concentration_for_freshwater_invertebrates = forms.FloatField(label='Acute Toxicity Target Concentration For Most Sensitive Freshwater Invertebrates')
    chronic_toxicity_target_concentration_for_freshwater_invertebrates = forms.FloatField(label='Chronic Toxicity Target Concentration For Most Sensitive Freshwater Invertebrates')    
    toxicity_target_concentration_for_nonlisted_vascular_plants = forms.FloatField(label='Toxicity Target Concentration for Most Sensitive Non-listed Vascular Plants')
    toxicity_target_concentration_for_listed_vascular_plants = forms.FloatField(label='Toxicity Target Concentration for Most Sensitive Listed Vascular Plants')
    toxicity_target_concentration_for_duckweed = forms.FloatField(label='Toxicity Target Concentration for Duckweed')
    lf_p_sediment = forms.FloatField(label='Large fish diet percent sediment')
    lf_p_phytoplankton = forms.FloatField(label='Large fish diet percent phytoplankton')
    lf_p_zooplankton = forms.FloatField(label='Large fish diet percent zooplankton')
    lf_p_benthic_invertebrates = forms.FloatField(label='Large fish diet percent benthic invertebrates')
    lf_p_filter_feeders = forms.FloatField(label='Large fish diet percent filter feeders')
    lf_p_small_fish = forms.FloatField(label='Large fish diet percent small fish')
    lf_p_medium_fish = forms.FloatField(label='Large fish diet percent medium fish')
    mf_p_sediment = forms.FloatField(label='Medium fish diet percent sediment')
    mf_p_phytoplankton = forms.FloatField(label='Medium fish diet percent phytoplankton')
    mf_p_zooplankton = forms.FloatField(label='Medium fish diet percent zooplankton')
    mf_p_benthic_invertebrates = forms.FloatField(label='Medium fish diet percent benthic invertebrates')
    mf_p_filter_feeders = forms.FloatField(label='Medium fish diet percent filter feeders')
    mf_p_small_fish = forms.FloatField(label='Medium fish diet percent small fish')
    sf_p_sediment = forms.FloatField(label='Small fish diet percent sediment')
    sf_p_phytoplankton = forms.FloatField(label='Small fish diet percent phytoplankton')
    sf_p_zooplankton = forms.FloatField(label='Small fish diet percent zooplankton')
    sf_p_benthic_invertebrates = forms.FloatField(label='Small fish diet percent benthic invertebrates')
    sf_p_filter_feeders = forms.FloatField(label='Small fish diet percent filter feeders')
    ff_p_sediment = forms.FloatField(label='Filter feeders diet percent sediment')
    ff_p_phytoplankton = forms.FloatField(label='Filter feeders diet percent phytoplankton')
    ff_p_zooplankton = forms.FloatField(label='Filter feeders diet percent zooplankton')
    ff_p_benthic_invertebrates = forms.FloatField(label='Filter feeders diet percent benthic invertebrates')
    beninv_p_sediment = forms.FloatField(label='Benthic invertebrates diet percent sediment')
    beninv_p_phytoplankton = forms.FloatField(label='Benthic invertebrates diet percent phytoplankton')
    beninv_p_zooplankton = forms.FloatField(label='Benthic invertebrates diet percent zooplankton')
    zoo_p_sediment = forms.FloatField(label='Zooplankton diet percent sediment')
    zoo_p_phytoplankton = forms.FloatField(label='Zooplankton diet percent phytoplankton')
    s_lipid = forms.FloatField(label='Sediment percent lipids')
    s_NLOM = forms.FloatField(label='Sediment percent non lipid organic matter')
    s_water = forms.FloatField(label='Sediment percent water')
    v_lb_phytoplankton = forms.FloatField(label='Phytoplankton percent lipids')
    v_nb_phytoplankton = forms.FloatField(label='Phytoplankton percent non lipid organic matter')
    v_wb_phytoplankton = forms.FloatField(label='Phytoplankton percent water')
    v_lb_zoo = forms.FloatField(label='Zooplankton percent lipids')
    v_nb_zoo = forms.FloatField(label='Zooplankton percent non lipid organic matter')
    v_wb_zoo = forms.FloatField(label='Zoopalnkton percent water')
    v_lb_beninv = forms.FloatField(label='Benthic invertebrates percent lipids')
    v_nb_beninv = forms.FloatField(label='Benthic invertebrates percent non lipid organic matter')
    v_wb_beninv = forms.FloatField(label='Benthic invertebrates percent water')
    v_lb_ff = forms.FloatField(label='Filter feeders percent lipids')
    v_nb_ff = forms.FloatField(label='Filter feeders percent non lipid organic matter')
    v_wb_ff = forms.FloatField(label='Filter feeders percent water')
    v_lb_sf = forms.FloatField(label='Small fish percent lipids')
    v_nb_sf = forms.FloatField(label='Small fish percent non lipid organic matter')
    v_wb_sf = forms.FloatField(label='Small fish percent water')
    v_lb_mf = forms.FloatField(label='Medium fish percent lipids')
    v_nb_mf = forms.FloatField(label='Medium fish percent non lipid organic matter')
    v_wb_mf = forms.FloatField(label='Medium fish percent water')
    v_lb_lf = forms.FloatField(label='Large fish percent lipids')
    v_nb_lf = forms.FloatField(label='Large fish percent non lipid organic matter')
    v_wb_lf = forms.FloatField(label='Large fish percent water')
    k1_phytoplankton = forms.FloatField(label='Phytoplankton k1 constant')
    k2_phytoplankton = forms.FloatField(label='Phytoplankton k2 constant')
    ke_phytoplankton = forms.FloatField(label='Phytoplankton ke constant')
    kd_phytoplankton = forms.FloatField(label='Phytoplankton kd constant')
    km_phytoplankton = forms.FloatField(label='Phytoplankton km constant')
    k1_zoo = forms.FloatField(label='Zooplankton k1 constant')
    k2_zoo = forms.FloatField(label='Zooplankton k2 constant')
    ke_zoo = forms.FloatField(label='Zooplankton ke constant')
    kd_zoo = forms.FloatField(label='Zooplankton kd constant')
    km_zoo = forms.FloatField(label='Zooplankton km constant')
    k1_beninv = forms.FloatField(label='Benthic invertebrates k1 constant')
    k2_beninv = forms.FloatField(label='Benthic invertebrates k2 constant')
    ke_beninv = forms.FloatField(label='Benthic invertebrates ke constant')
    kd_beninv = forms.FloatField(label='Benthic invertebrates kd constant')
    km_beninv = forms.FloatField(label='Benthic invertebrates km constant')
    k1_ff = forms.FloatField(label='Filter feeders k1 constant')
    k2_ff = forms.FloatField(label='Filter feeders k2 constant')
    ke_ff = forms.FloatField(label='Filter feeders ke constant')
    kd_ff = forms.FloatField(label='Filter feeders kd constant')
    km_ff = forms.FloatField(label='Filter feeders km constant')
    k1_sf = forms.FloatField(label='Small fish k1 constant')
    k2_sf = forms.FloatField(label='Small fish k2 constant')
    ke_sf = forms.FloatField(label='Small fish ke constant')
    kd_sf = forms.FloatField(label='Small fish kd constant')
    km_sf = forms.FloatField(label='Small fish km constant')
    k1_mf = forms.FloatField(label='Medium fish k1 constant')
    k2_mf = forms.FloatField(label='Medium fish k2 constant')
    ke_mf = forms.FloatField(label='Medium fish ke constant')
    kd_mf = forms.FloatField(label='Medium fish kd constant')
    km_mf = forms.FloatField(label='Medium fish km constant')
    k1_lf = forms.FloatField(label='Large fish k1 constant')
    k2_lf = forms.FloatField(label='Large fish k2 constant')
    ke_lf = forms.FloatField(label='Large fish ke constant')
    kd_lf = forms.FloatField(label='Large fish kd constant')
    km_lf = forms.FloatField(label='Large fish km constant')
    s_respire = forms.FloatField(label='Sediment respire pore water')
    phyto_respire = forms.FloatField(label='Phytoplankton respire pore water')
    zoo_respire = forms.FloatField(label='Zooplankton respire pore water')
    beninv_respire = forms.FloatField(label='Benthic invertebrates respire pore water')
    ff_respire = forms.FloatField(label='Filter feeders respire pore water')
    sf_respire = forms.FloatField(label='Small fish respire pore water')
    mf_respire = forms.FloatField(label='Medium fish respire pore water')
    lf_respire = forms.FloatField(label='Large fish respire pore water')
    mo_phytoplankton = forms.FloatField(label='Fraction of respiratory ventilation involving overlying water')
    mp_phytoplankton = forms.FloatField(label='Fraction of respiratory ventilation involving pore water')
    kg_phytoplankton = forms.FloatField(label='Phytoplankton growth rate constant')
    created = db.DateTimeProperty(auto_now_add=True)    
