import google.appengine.ext.db as db
import datetime
import time
import logging
import webapp2 as webapp
from django.utils import simplejson
from google.appengine.ext.webapp.util import run_wsgi_app
from google.appengine.ext.webapp import template
from google.appengine.api import users

class AquaticToxicity(db.Model):
    config_name = db.StringProperty()
    user = db.UserProperty()
    acute_toxicity_target_concentration_for_freshwater_fish = db.FloatProperty()
    chronic_toxicity_target_concentration_for_freshwater_fish = db.FloatProperty()
    acute_toxicity_target_concentration_for_freshwater_invertebrates = db.FloatProperty()
    chronic_toxicity_target_concentration_for_freshwater_invertebrates = db.FloatProperty() 
    toxicity_target_concentration_for_nonlisted_vascular_plants = db.FloatProperty()
    toxicity_target_concentration_for_listed_vascular_plants = db.FloatProperty()
    toxicity_target_concentration_for_duckweed = db.FloatProperty()
    lf_p_sediment = db.FloatProperty()
    lf_p_phytoplankton = db.FloatProperty()
    lf_p_zooplankton = db.FloatProperty()
    lf_p_benthic_invertebrates = db.FloatProperty()
    lf_p_filter_feeders = db.FloatProperty()
    lf_p_small_fish = db.FloatProperty()
    lf_p_medium_fish = db.FloatProperty()
    mf_p_sediment = db.FloatProperty()
    mf_p_phytoplankton = db.FloatProperty()
    mf_p_zooplankton = db.FloatProperty()
    mf_p_benthic_invertebrates = db.FloatProperty()
    mf_p_filter_feeders = db.FloatProperty()
    mf_p_small_fish = db.FloatProperty()
    sf_p_sediment = db.FloatProperty()
    sf_p_phytoplankton = db.FloatProperty()
    sf_p_zooplankton = db.FloatProperty()
    sf_p_benthic_invertebrates = db.FloatProperty()
    sf_p_filter_feeders = db.FloatProperty()
    ff_p_sediment = db.FloatProperty()
    ff_p_phytoplankton = db.FloatProperty()
    ff_p_zooplankton = db.FloatProperty()
    ff_p_benthic_invertebrates = db.FloatProperty()
    beninv_p_sediment = db.FloatProperty()
    beninv_p_phytoplankton = db.FloatProperty()
    beninv_p_zooplankton = db.FloatProperty()
    zoo_p_sediment = db.FloatProperty()
    zoo_p_phytoplankton = db.FloatProperty()
    s_lipid = db.FloatProperty()
    s_NLOM = db.FloatProperty()
    s_water = db.FloatProperty()
    v_lb_phytoplankton = db.FloatProperty()
    v_nb_phytoplankton = db.FloatProperty()
    v_wb_phytoplankton = db.FloatProperty()
    v_lb_zoo = db.FloatProperty()
    v_nb_zoo = db.FloatProperty()
    v_wb_zoo = db.FloatProperty()
    v_lb_beninv = db.FloatProperty()
    v_nb_beninv = db.FloatProperty()
    v_wb_beninv = db.FloatProperty()
    v_lb_ff = db.FloatProperty()
    v_nb_ff = db.FloatProperty()
    v_wb_ff = db.FloatProperty()
    v_lb_sf = db.FloatProperty()
    v_nb_sf = db.FloatProperty()
    v_wb_sf = db.FloatProperty()
    v_lb_mf = db.FloatProperty()
    v_nb_mf = db.FloatProperty()
    v_wb_mf = db.FloatProperty()
    v_lb_lf = db.FloatProperty()
    v_nb_lf = db.FloatProperty()
    v_wb_lf = db.FloatProperty()
    k1_phytoplankton = db.FloatProperty()
    k2_phytoplankton = db.FloatProperty()
    ke_phytoplankton = db.FloatProperty()
    kd_phytoplankton = db.FloatProperty()
    km_phytoplankton = db.FloatProperty()
    k1_zoo = db.FloatProperty()
    k2_zoo = db.FloatProperty()
    ke_zoo = db.FloatProperty()
    kd_zoo = db.FloatProperty()
    km_zoo = db.FloatProperty()
    k1_beninv = db.FloatProperty()
    k2_beninv = db.FloatProperty()
    ke_beninv = db.FloatProperty()
    kd_beninv = db.FloatProperty()
    km_beninv = db.FloatProperty()
    k1_ff = db.FloatProperty()
    k2_ff = db.FloatProperty()
    ke_ff = db.FloatProperty()
    kd_ff = db.FloatProperty()
    km_ff = db.FloatProperty()
    k1_sf = db.FloatProperty()
    k2_sf = db.FloatProperty()
    ke_sf = db.FloatProperty()
    kd_sf = db.FloatProperty()
    km_sf = db.FloatProperty()
    k1_mf = db.FloatProperty()
    k2_mf = db.FloatProperty()
    ke_mf = db.FloatProperty()
    kd_mf = db.FloatProperty()
    km_mf = db.FloatProperty()
    k1_lf = db.FloatProperty()
    k2_lf = db.FloatProperty()
    ke_lf = db.FloatProperty()
    kd_lf = db.FloatProperty()
    km_lf = db.FloatProperty()
    s_respire = db.FloatProperty()
    phyto_respire = db.FloatProperty()
    zoo_respire = db.FloatProperty()
    beninv_respire = db.FloatProperty()
    ff_respire = db.FloatProperty()
    sfish_respire = db.FloatProperty()
    mfish_respire = db.FloatProperty()
    lfish_respire = db.FloatProperty()
    mo_phytoplankton = db.FloatProperty()
    mp_phytoplankton = db.FloatProperty()
    kg_phytoplankton = db.FloatProperty()
    created = db.DateTimeProperty(auto_now_add=True)
