application: pypest
version: jon
runtime: python27
api_version: 1

default_expiration: "5d 12h"

threadsafe: false

libraries:
- name: numpy
  version: latest
- name: webapp2
  version: latest
- name: django
  version: "1.3"

- name: PIL
  version: latest

env_variables:
  UBERTOOL_BATCH_SERVER: 'http://www.chancedelphia.com:8887/'

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.gz
- ^(.*/)?.*\.bak
- ^(geneec/geneec_picloud/.*)
- ^(przm/przm_picloud/.*)
- ^(pfam/pfam_picloud/.*)
- ^(generatepdf/generatepdf_picloud/.*)$

handlers:
- url: /
  script: landingJon.py 
- url: /index.html
  script: landingJon.py 
- url: /admin.html
  script: admin.py
- url: /eco_index.html
  script: main.py 
- url: /hh_index.html
  script: hh_main.py 
- url: /pop_index.html
  script: pop_main.py 
- url: /about.html
  script: about.py
- url: /pdf.html
  script: pdf_output.py
- url: /html.html
  script: html_output.py

# All URLs beginning with /stylesheets are treated as paths to static files in
# the stylesheets/ directory. Note that static_dir handlers do not use a
# regular expression for the URL pattern, only a prefix.
- url: /stylesheets
  static_dir: stylesheets
- url: /raphael
  static_dir: raphael
- url: /images
  static_dir: images
- url: /pdfs
  static_dir: pdfs
- url: /csvs
  static_dir: csvs
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /templates/popup.html
  static_files: templates/popup.html
  upload: templates/popup.html

##UBERTOOL INPUT PAGES##
#output
- url: /select_chemical_output.html
  script: ubertool/select_chemical_output.py
  login: required 
- url: /use_output.html
  script: ubertool/use_output.py
  login: required 
- url: /pesticide_properties_output.html
  script: ubertool/pesticide_properties_output.py
  login: required 
- url: /exposure_concentrations_output.html
  script: ubertool/exposure_concentrations_output.py
  login: required 
- url: /aquatic_toxicity_output.html
  script: ubertool/aquatic_toxicity_output.py
  login: required 
- url: /ecosystem_inputs_output.html
  script: ubertool/ecosystem_inputs_output.py
  login: required 
- url: /terrestrial_toxicity_output.html
  script: ubertool/terrestrial_toxicity_output.py
  login: required 
#ubertool batch output
- url: /run_ubertool_batchoutput.html
  script: ubertool/run_ubertool_batch_output.py
  login: required
- url: /ubertool-batch-configuration
  script: ubertool/run_ubertool_output.py
- url: /run_ubertool_output.html
  script: ubertool/run_ubertool_output.py
  login: required 
##UNTESTED models##
#description
- url: /(.*?)_description.html
  script: \1/\1_description.py
#input
- url: /(.*?)_input.html
  script: \1/\1_input.py
#output
- url: /(.*?)_output.html
  script: \1/\1_output.py  
#algorithms
- url: /(.*?)_algorithms.html
  script: \1/\1_algorithm.py    
#references
- url: /(.*?)_references.html
  script: \1/\1_references.py 
#qaqc
- url: /(.*?)_qaqc.html
  script: \1/\1_qaqc.py 
#batch
- url: /(.*?)_batchinput.html
  script: \1/\1_batchinput.py
#batch_output
- url: /(.*?)_batchoutput.html
  script: \1/\1_batchoutput.py

##TESTED models##
#description
- url: /(.*?)/(.*?)_description.html
  script: \1/\2/\2_description.py
#input
- url: /(.*?)/(.*?)_input.html
  script: \1/\2/\2_input.py
#output
- url: /(.*?)/(.*?)_output.html
  script: \1/\2/\2_output.py  
#algorithms
- url: /(.*?)/(.*?)_algorithms.html
  script: \1/\2/\2_algorithm.py    
#references
- url: /(.*?)/(.*?)_references.html
  script: \1/\2/\2_references.py 
#qaqc
- url: /(.*?)/(.*?)_qaqc.html
  script: \1/\2/\2_qaqc.py 
#qaqc_output
- url: /(.*?)/(.*?)_qaqc_output.html
  script: \1/\2/\2_qaqc_output.py


#USER pages
- url: /user.html
  script: user/user_input.py   
  login: required

- url: /user_output.html
  script: user/user_output.py
  login: required

#select chemical
- url: /select_chemical.html
  script: ubertool/select_chemical_input.py
  login: required

#use service
- url: /use/(.*)
  script: ubertool/use.py
  login: required
#use service
- url: /use-config-names
  script: ubertool/use.py
  login: required
#aqua service
- url: /aqua-config-names
  script: ubertool/aquatic_toxicity.py
  login: required
- url: /aqua/(.*)
  script: ubertool/aquatic_toxicity.py
  login: required
#expo service
- url: /expo-config-names
  script: ubertool/exposure_concentrations.py
  login: required
- url: /expo/(.*)
  script: ubertool/exposure_concentrations.py
  login: required
#expo service
- url: /pest-config-names
  script: ubertool/pesticide_properties.py
  login: required
#eco service
- url: /eco-config-names
  script: ubertool/ecosystem_inputs.py
  login: required
#expo service
- url: /terra-config-names
  script: ubertool/terrestrial_toxicity.py
  login: required
- url: /terrestrial/(.*)
  script: ubertool/terrestrial_toxicity.py
  login: required
#pest service
- url: /pest/(.*)
  script: ubertool/pesticide_properties.py
  login: required

#Model method service for asynchronous invocation
- url: /msed
  script: rice/rice_model.py 

#ecosys service
- url: /ecosys/(.*)
  script: ubertool/ecosystem_inputs.py
  login: required

#terrestrial service
- url: /terrestrial/(.*)
  script: ubertool/terrestrial_toxicity.py
  login: required

#ubertool service
- url: /ubertool/all_props/(.*)
  script: ubertool/ubertool_all_properties.py
  login: required

#ubertool service
- url: /ubertool
  script: ubertool/ubertool_all_properties.py
  login: required

#ubertool service
- url: /ubertool/(.*)
  script: ubertool/ubertool.py
  login: required

- url: /ubertool-stats
  script: ubertool/ubertool.py
  login: required

#cas service
- url: /cas/(.*)
  script: CAS/cas.py
  login: required

#batch service
- url: /batch
  script: batch/batch_processor.py
  login: required

#batch retrieval service
- url: /batch_results/(.*)
  script: batch/batch.py
  login: required

#batch retrieval service
- url: /batch_configs
  script: batch/batch.py
  login: required 

#use label site data
- url: /site_data.html
  script: ubertool/use_input.py
  login: required
#  login: required
#pesticide properties
- url: /pesticide_properties.html
  script: ubertool/pesticide_properties_input.py
  login: required
#exposure concentrations
- url: /exposure_concentrations.html
  script: ubertool/exposure_concentrations_input.py
  login: required
#aquatic toxicity
- url: /aquatic_toxicity.html
  script: ubertool/aquatic_toxicity_input.py
  login: required
#terrestrial toxicity
- url: /terrestrial_toxicity.html
  script: ubertool/terrestrial_toxicity_input.py
  login: required
#ecosystem inputs
- url: /ecosystem_inputs.html
  script: ubertool/ecosystem_inputs_input.py
  login: required
#run ubertool
- url: /run_ubertool.html
  script: ubertool/run_ubertool_input.py  
  login: required

#ESA workshop
- url: /esa_workshop.html
  script: esa_workshop/esa_workshop.py  

#file not found
- url: /.*
  script: file_not_found.py
