
      REAL*4 DDW , DDS , DDG , DDW1 , DDS1 , DDG1 , DDW2 , DDS2 , DDG2 ,&
     &       DDKw12 , DDKw13 , DDKw23 , DDKs12 , DDKs13 , DDKs23 ,      &
     &       DDKw112 , DDKw113 , DDKw123 , DDKs112 , DDKs113 , DDKs123 ,&
     &       DDKw212 , DDKw213 , DDKw223 , DDKs212 , DDKs213 , DDKs223
      COMMON /DPSTR41/ DDKw12(ncmpts) , DDKw13(ncmpts) , DDKw23(ncmpts) &
     &                 , DDKs12(ncmpts) , DDKs13(ncmpts) ,              &
     &                 DDKs23(ncmpts) , DDKw112(ncmpts) ,               &
     &                 DDKw113(ncmpts) , DDKw123(ncmpts) ,              &
     &                 DDKs112(ncmpts) , DDKs113(ncmpts) ,              &
     &                 DDKs123(ncmpts) , DDKw212(ncmpts) ,              &
     &                 DDKw213(ncmpts) , DDKw223(ncmpts) ,              &
     &                 DDKs212(ncmpts) , DDKs213(ncmpts) ,              &
     &                 DDKs223(ncmpts)
      COMMON /DPSTR42/ DDW(3,ncmpts) , DDS(3,ncmpts) , DDG(3,ncmpts) ,  &
     &                 DDW1(3,ncmpts) , DDS1(3,ncmpts) , DDG1(3,ncmpts) &
     &                 , DDW2(3,ncmpts) , DDS2(3,ncmpts) ,              &
     &                 DDG2(3,ncmpts)
